# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from antx.server.user import user_rpc_pb2 as antx_dot_server_dot_user_dot_user__rpc__pb2


class UserServiceStub(object):
    """用户服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserRegister = channel.unary_unary(
                '/antx.server.user.UserService/UserRegister',
                request_serializer=antx_dot_server_dot_user_dot_user__rpc__pb2.UserRegisterRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_user_dot_user__rpc__pb2.UserRegisterResponse.FromString,
                _registered_method=True)
        self.GetUserByAddress = channel.unary_unary(
                '/antx.server.user.UserService/GetUserByAddress',
                request_serializer=antx_dot_server_dot_user_dot_user__rpc__pb2.GetUserByAddressRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_user_dot_user__rpc__pb2.GetUserByAddressResponse.FromString,
                _registered_method=True)
        self.BindReferral = channel.unary_unary(
                '/antx.server.user.UserService/BindReferral',
                request_serializer=antx_dot_server_dot_user_dot_user__rpc__pb2.BindReferralRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_user_dot_user__rpc__pb2.BindReferralResponse.FromString,
                _registered_method=True)
        self.GetUserReferralPage = channel.unary_unary(
                '/antx.server.user.UserService/GetUserReferralPage',
                request_serializer=antx_dot_server_dot_user_dot_user__rpc__pb2.GetUserReferralPageRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_user_dot_user__rpc__pb2.GetUserReferralPageResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """用户服务
    """

    def UserRegister(self, request, context):
        """onboard
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByAddress(self, request, context):
        """get user(by address)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BindReferral(self, request, context):
        """bind referral
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserReferralPage(self, request, context):
        """Get UserReferral Page
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.UserRegister,
                    request_deserializer=antx_dot_server_dot_user_dot_user__rpc__pb2.UserRegisterRequest.FromString,
                    response_serializer=antx_dot_server_dot_user_dot_user__rpc__pb2.UserRegisterResponse.SerializeToString,
            ),
            'GetUserByAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByAddress,
                    request_deserializer=antx_dot_server_dot_user_dot_user__rpc__pb2.GetUserByAddressRequest.FromString,
                    response_serializer=antx_dot_server_dot_user_dot_user__rpc__pb2.GetUserByAddressResponse.SerializeToString,
            ),
            'BindReferral': grpc.unary_unary_rpc_method_handler(
                    servicer.BindReferral,
                    request_deserializer=antx_dot_server_dot_user_dot_user__rpc__pb2.BindReferralRequest.FromString,
                    response_serializer=antx_dot_server_dot_user_dot_user__rpc__pb2.BindReferralResponse.SerializeToString,
            ),
            'GetUserReferralPage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserReferralPage,
                    request_deserializer=antx_dot_server_dot_user_dot_user__rpc__pb2.GetUserReferralPageRequest.FromString,
                    response_serializer=antx_dot_server_dot_user_dot_user__rpc__pb2.GetUserReferralPageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antx.server.user.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antx.server.user.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """用户服务
    """

    @staticmethod
    def UserRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.user.UserService/UserRegister',
            antx_dot_server_dot_user_dot_user__rpc__pb2.UserRegisterRequest.SerializeToString,
            antx_dot_server_dot_user_dot_user__rpc__pb2.UserRegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.user.UserService/GetUserByAddress',
            antx_dot_server_dot_user_dot_user__rpc__pb2.GetUserByAddressRequest.SerializeToString,
            antx_dot_server_dot_user_dot_user__rpc__pb2.GetUserByAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BindReferral(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.user.UserService/BindReferral',
            antx_dot_server_dot_user_dot_user__rpc__pb2.BindReferralRequest.SerializeToString,
            antx_dot_server_dot_user_dot_user__rpc__pb2.BindReferralResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserReferralPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.user.UserService/GetUserReferralPage',
            antx_dot_server_dot_user_dot_user__rpc__pb2.GetUserReferralPageRequest.SerializeToString,
            antx_dot_server_dot_user_dot_user__rpc__pb2.GetUserReferralPageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
