# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antx/chain/demo/post.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61ntx/chain/demo/post.proto\x12\x0f\x61ntx.chain.demo\"Z\n\x04Post\x12\x14\n\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n\x04\x62ody\x18\x02 \x01(\tR\x04\x62ody\x12\x18\n\x07\x63reator\x18\x03 \x01(\tR\x07\x63reator\x12\x0e\n\x02id\x18\x04 \x01(\x04R\x02idBX\n\x1e\x65xchange.antx.proto.chain.demoB\tPostProtoP\x01Z)github.com/antxprotocol/antx/x/demo/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antx.chain.demo.post_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036exchange.antx.proto.chain.demoB\tPostProtoP\001Z)github.com/antxprotocol/antx/x/demo/types'
  _globals['_POST']._serialized_start=47
  _globals['_POST']._serialized_end=137
# @@protoc_insertion_point(module_scope)
