# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from antx.chain.demo import tx_pb2 as antx_dot_chain_dot_demo_dot_tx__pb2


class MsgStub(object):
    """Msg defines the Msg service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateParams = channel.unary_unary(
                '/antx.chain.demo.Msg/UpdateParams',
                request_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateParams.SerializeToString,
                response_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateParamsResponse.FromString,
                _registered_method=True)
        self.CreatePost = channel.unary_unary(
                '/antx.chain.demo.Msg/CreatePost',
                request_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreatePost.SerializeToString,
                response_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreatePostResponse.FromString,
                _registered_method=True)
        self.UpdatePost = channel.unary_unary(
                '/antx.chain.demo.Msg/UpdatePost',
                request_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdatePost.SerializeToString,
                response_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdatePostResponse.FromString,
                _registered_method=True)
        self.CreateProduct = channel.unary_unary(
                '/antx.chain.demo.Msg/CreateProduct',
                request_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateProduct.SerializeToString,
                response_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateProductResponse.FromString,
                _registered_method=True)
        self.UpdateProduct = channel.unary_unary(
                '/antx.chain.demo.Msg/UpdateProduct',
                request_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateProduct.SerializeToString,
                response_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateProductResponse.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/antx.chain.demo.Msg/DeleteProduct',
                request_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteProduct.SerializeToString,
                response_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteProductResponse.FromString,
                _registered_method=True)
        self.CreateCategory = channel.unary_unary(
                '/antx.chain.demo.Msg/CreateCategory',
                request_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateCategory.SerializeToString,
                response_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateCategoryResponse.FromString,
                _registered_method=True)
        self.UpdateCategory = channel.unary_unary(
                '/antx.chain.demo.Msg/UpdateCategory',
                request_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateCategory.SerializeToString,
                response_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateCategoryResponse.FromString,
                _registered_method=True)
        self.DeleteCategory = channel.unary_unary(
                '/antx.chain.demo.Msg/DeleteCategory',
                request_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteCategory.SerializeToString,
                response_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteCategoryResponse.FromString,
                _registered_method=True)
        self.CreateAd = channel.unary_unary(
                '/antx.chain.demo.Msg/CreateAd',
                request_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateAd.SerializeToString,
                response_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateAdResponse.FromString,
                _registered_method=True)
        self.UpdateAd = channel.unary_unary(
                '/antx.chain.demo.Msg/UpdateAd',
                request_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateAd.SerializeToString,
                response_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateAdResponse.FromString,
                _registered_method=True)
        self.DeleteAd = channel.unary_unary(
                '/antx.chain.demo.Msg/DeleteAd',
                request_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteAd.SerializeToString,
                response_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteAdResponse.FromString,
                _registered_method=True)


class MsgServicer(object):
    """Msg defines the Msg service.
    """

    def UpdateParams(self, request, context):
        """UpdateParams defines a (governance) operation for updating the module
        parameters. The authority defaults to the x/gov module account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePost(self, request, context):
        """CreatePost defines the CreatePost RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePost(self, request, context):
        """UpdatePost defines the UpdatePost RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProduct(self, request, context):
        """CreateProduct defines the CreateProduct RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """UpdateProduct defines the UpdateProduct RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """DeleteProduct defines the DeleteProduct RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCategory(self, request, context):
        """CreateCategory defines the CreateCategory RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCategory(self, request, context):
        """UpdateCategory defines the UpdateCategory RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCategory(self, request, context):
        """DeleteCategory defines the DeleteCategory RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAd(self, request, context):
        """CreateAd defines the CreateAd RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAd(self, request, context):
        """UpdateAd defines the UpdateAd RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAd(self, request, context):
        """DeleteAd defines the DeleteAd RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateParams': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParams,
                    request_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateParams.FromString,
                    response_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateParamsResponse.SerializeToString,
            ),
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreatePost.FromString,
                    response_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreatePostResponse.SerializeToString,
            ),
            'UpdatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePost,
                    request_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdatePost.FromString,
                    response_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdatePostResponse.SerializeToString,
            ),
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateProduct.FromString,
                    response_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateProductResponse.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateProduct.FromString,
                    response_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateProductResponse.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteProduct.FromString,
                    response_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteProductResponse.SerializeToString,
            ),
            'CreateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCategory,
                    request_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateCategory.FromString,
                    response_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateCategoryResponse.SerializeToString,
            ),
            'UpdateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCategory,
                    request_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateCategory.FromString,
                    response_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateCategoryResponse.SerializeToString,
            ),
            'DeleteCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCategory,
                    request_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteCategory.FromString,
                    response_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteCategoryResponse.SerializeToString,
            ),
            'CreateAd': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAd,
                    request_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateAd.FromString,
                    response_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateAdResponse.SerializeToString,
            ),
            'UpdateAd': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAd,
                    request_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateAd.FromString,
                    response_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateAdResponse.SerializeToString,
            ),
            'DeleteAd': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAd,
                    request_deserializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteAd.FromString,
                    response_serializer=antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteAdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antx.chain.demo.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antx.chain.demo.Msg', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Msg defines the Msg service.
    """

    @staticmethod
    def UpdateParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.demo.Msg/UpdateParams',
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateParams.SerializeToString,
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.demo.Msg/CreatePost',
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreatePost.SerializeToString,
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreatePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.demo.Msg/UpdatePost',
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdatePost.SerializeToString,
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdatePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.demo.Msg/CreateProduct',
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateProduct.SerializeToString,
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.demo.Msg/UpdateProduct',
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateProduct.SerializeToString,
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.demo.Msg/DeleteProduct',
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteProduct.SerializeToString,
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.demo.Msg/CreateCategory',
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateCategory.SerializeToString,
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.demo.Msg/UpdateCategory',
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateCategory.SerializeToString,
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.demo.Msg/DeleteCategory',
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteCategory.SerializeToString,
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.demo.Msg/CreateAd',
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateAd.SerializeToString,
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgCreateAdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.demo.Msg/UpdateAd',
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateAd.SerializeToString,
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgUpdateAdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.demo.Msg/DeleteAd',
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteAd.SerializeToString,
            antx_dot_chain_dot_demo_dot_tx__pb2.MsgDeleteAdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
