# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antex/server/price/price_rpc.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'antex/server/price/price_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antex_proto.antex.chain.price import price_pb2 as antex_dot_chain_dot_price_dot_price__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"antex/server/price/price_rpc.proto\x12\x12\x61ntex.server.price\x1a\x1d\x61ntex/chain/price/price.proto\"=\n\x1aGetIndexPriceConfigRequest\x12\x1f\n\x0b\x65xchange_id\x18\x01 \x03(\x03R\nexchangeId\"n\n\x1bGetIndexPriceConfigResponse\x12O\n\x0cprice_config\x18\x01 \x03(\x0b\x32,.antex.server.price.ExchangeIndexPriceConfigR\x0bpriceConfig\"\x8c\x01\n\x18\x45xchangeIndexPriceConfig\x12\x1f\n\x0b\x65xchange_id\x18\x01 \x01(\x03R\nexchangeId\x12O\n\rexchange_info\x18\x02 \x03(\x0b\x32*.antex.server.price.IndexPriceExchangeInfoR\x0c\x65xchangeInfo\"|\n\x16IndexPriceExchangeInfo\x12#\n\rexchange_name\x18\x01 \x01(\tR\x0c\x65xchangeName\x12%\n\x0e\x65xchange_quote\x18\x02 \x01(\tR\rexchangeQuote\x12\x16\n\x06weight\x18\x03 \x01(\tR\x06weight\"\x8b\x01\n\x15\x46orcePushPriceRequest\x12\x1f\n\x0b\x65xchange_id\x18\x01 \x01(\x03R\nexchangeId\x12;\n\nprice_type\x18\x02 \x01(\x0e\x32\x1c.antex.chain.price.PriceTypeR\tpriceType\x12\x14\n\x05price\x18\x03 \x01(\tR\x05price\"\x18\n\x16\x46orcePushPriceResponse\"\x1a\n\x18GetFlatTokenPriceRequest\"g\n\x19GetFlatTokenPriceResponse\x12$\n\x0eusdc_usd_price\x18\x01 \x01(\tR\x0cusdcUsdPrice\x12$\n\x0eusdt_usd_price\x18\x02 \x01(\tR\x0cusdtUsdPrice2\xe1\x02\n\x0cPriceService\x12v\n\x13GetIndexPriceConfig\x12..antex.server.price.GetIndexPriceConfigRequest\x1a/.antex.server.price.GetIndexPriceConfigResponse\x12g\n\x0e\x46orcePushPrice\x12).antex.server.price.ForcePushPriceRequest\x1a*.antex.server.price.ForcePushPriceResponse\x12p\n\x11GetFlatTokenPrice\x12,.antex.server.price.GetFlatTokenPriceRequest\x1a-.antex.server.price.GetFlatTokenPriceResponseB4\n!exchange.antex.proto.server.priceB\rPriceRpcProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antex.server.price.price_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!exchange.antex.proto.server.priceB\rPriceRpcProtoP\001'
  _globals['_GETINDEXPRICECONFIGREQUEST']._serialized_start=89
  _globals['_GETINDEXPRICECONFIGREQUEST']._serialized_end=150
  _globals['_GETINDEXPRICECONFIGRESPONSE']._serialized_start=152
  _globals['_GETINDEXPRICECONFIGRESPONSE']._serialized_end=262
  _globals['_EXCHANGEINDEXPRICECONFIG']._serialized_start=265
  _globals['_EXCHANGEINDEXPRICECONFIG']._serialized_end=405
  _globals['_INDEXPRICEEXCHANGEINFO']._serialized_start=407
  _globals['_INDEXPRICEEXCHANGEINFO']._serialized_end=531
  _globals['_FORCEPUSHPRICEREQUEST']._serialized_start=534
  _globals['_FORCEPUSHPRICEREQUEST']._serialized_end=673
  _globals['_FORCEPUSHPRICERESPONSE']._serialized_start=675
  _globals['_FORCEPUSHPRICERESPONSE']._serialized_end=699
  _globals['_GETFLATTOKENPRICEREQUEST']._serialized_start=701
  _globals['_GETFLATTOKENPRICEREQUEST']._serialized_end=727
  _globals['_GETFLATTOKENPRICERESPONSE']._serialized_start=729
  _globals['_GETFLATTOKENPRICERESPONSE']._serialized_end=832
  _globals['_PRICESERVICE']._serialized_start=835
  _globals['_PRICESERVICE']._serialized_end=1188
# @@protoc_insertion_point(module_scope)
