# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from antx.server.stats import stats_rpc_pb2 as antx_dot_server_dot_stats_dot_stats__rpc__pb2


class StatsServiceStub(object):
    """统计服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTotalStatsSummary = channel.unary_unary(
                '/antx.server.stats.StatsService/GetTotalStatsSummary',
                request_serializer=antx_dot_server_dot_stats_dot_stats__rpc__pb2.GetTotalStatsSummaryRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_stats_dot_stats__rpc__pb2.GetTotalStatsSummaryResponse.FromString,
                _registered_method=True)
        self.GetStatsSummary = channel.unary_unary(
                '/antx.server.stats.StatsService/GetStatsSummary',
                request_serializer=antx_dot_server_dot_stats_dot_stats__rpc__pb2.GetStatsSummaryRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_stats_dot_stats__rpc__pb2.GetStatsSummaryResponse.FromString,
                _registered_method=True)


class StatsServiceServicer(object):
    """统计服务
    """

    def GetTotalStatsSummary(self, request, context):
        """获取全局统计数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatsSummary(self, request, context):
        """查询统计数据列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTotalStatsSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalStatsSummary,
                    request_deserializer=antx_dot_server_dot_stats_dot_stats__rpc__pb2.GetTotalStatsSummaryRequest.FromString,
                    response_serializer=antx_dot_server_dot_stats_dot_stats__rpc__pb2.GetTotalStatsSummaryResponse.SerializeToString,
            ),
            'GetStatsSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatsSummary,
                    request_deserializer=antx_dot_server_dot_stats_dot_stats__rpc__pb2.GetStatsSummaryRequest.FromString,
                    response_serializer=antx_dot_server_dot_stats_dot_stats__rpc__pb2.GetStatsSummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antx.server.stats.StatsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antx.server.stats.StatsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatsService(object):
    """统计服务
    """

    @staticmethod
    def GetTotalStatsSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.stats.StatsService/GetTotalStatsSummary',
            antx_dot_server_dot_stats_dot_stats__rpc__pb2.GetTotalStatsSummaryRequest.SerializeToString,
            antx_dot_server_dot_stats_dot_stats__rpc__pb2.GetTotalStatsSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatsSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.stats.StatsService/GetStatsSummary',
            antx_dot_server_dot_stats_dot_stats__rpc__pb2.GetStatsSummaryRequest.SerializeToString,
            antx_dot_server_dot_stats_dot_stats__rpc__pb2.GetStatsSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
