# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antx/server/offchain/offchain_rpc.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antx.chain.offchain import offchain_pb2 as antx_dot_chain_dot_offchain_dot_offchain__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'antx/server/offchain/offchain_rpc.proto\x12\x14\x61ntx.server.offchain\x1a\"antx/chain/offchain/offchain.proto\"~\n$GetOffchainEventByBlockHeightRequest\x12!\n\x0c\x62lock_height\x18\x01 \x01(\x04R\x0b\x62lockHeight\x12\x12\n\x04size\x18\x02 \x01(\rR\x04size\x12\x1f\n\x0boffset_data\x18\x03 \x01(\tR\noffsetData\"\xa5\x01\n%GetOffchainEventByBlockHeightResponse\x12I\n\x0eoffchain_event\x18\x01 \x03(\x0b\x32\".antx.chain.offchain.OffchainEventR\roffchainEvent\x12\x31\n\x15next_page_offset_data\x18\x02 \x01(\tR\x12nextPageOffsetData\"o\n\x1fGetOffchainEventByTxHashRequest\x12\x17\n\x07tx_hash\x18\x01 \x01(\tR\x06txHash\x12\x12\n\x04size\x18\x02 \x01(\rR\x04size\x12\x1f\n\x0boffset_data\x18\x03 \x01(\tR\noffsetData\"\xa0\x01\n GetOffchainEventByTxHashResponse\x12I\n\x0eoffchain_event\x18\x01 \x03(\x0b\x32\".antx.chain.offchain.OffchainEventR\roffchainEvent\x12\x31\n\x15next_page_offset_data\x18\x02 \x01(\tR\x12nextPageOffsetData2\xb8\x02\n\x0fOffchainService\x12\x98\x01\n\x1dGetOffchainEventByBlockHeight\x12:.antx.server.offchain.GetOffchainEventByBlockHeightRequest\x1a;.antx.server.offchain.GetOffchainEventByBlockHeightResponse\x12\x89\x01\n\x18GetOffchainEventByTxHash\x12\x35.antx.server.offchain.GetOffchainEventByTxHashRequest\x1a\x36.antx.server.offchain.GetOffchainEventByTxHashResponseB9\n#exchange.antx.proto.server.offchainB\x10OffchainRpcProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antx.server.offchain.offchain_rpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#exchange.antx.proto.server.offchainB\020OffchainRpcProtoP\001'
  _globals['_GETOFFCHAINEVENTBYBLOCKHEIGHTREQUEST']._serialized_start=101
  _globals['_GETOFFCHAINEVENTBYBLOCKHEIGHTREQUEST']._serialized_end=227
  _globals['_GETOFFCHAINEVENTBYBLOCKHEIGHTRESPONSE']._serialized_start=230
  _globals['_GETOFFCHAINEVENTBYBLOCKHEIGHTRESPONSE']._serialized_end=395
  _globals['_GETOFFCHAINEVENTBYTXHASHREQUEST']._serialized_start=397
  _globals['_GETOFFCHAINEVENTBYTXHASHREQUEST']._serialized_end=508
  _globals['_GETOFFCHAINEVENTBYTXHASHRESPONSE']._serialized_start=511
  _globals['_GETOFFCHAINEVENTBYTXHASHRESPONSE']._serialized_end=671
  _globals['_OFFCHAINSERVICE']._serialized_start=674
  _globals['_OFFCHAINSERVICE']._serialized_end=986
# @@protoc_insertion_point(module_scope)
