# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antx/server/price/price_rpc.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antx.chain.price import price_pb2 as antx_dot_chain_dot_price_dot_price__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!antx/server/price/price_rpc.proto\x12\x11\x61ntx.server.price\x1a\x1c\x61ntx/chain/price/price.proto\"=\n\x1aGetIndexPriceConfigRequest\x12\x1f\n\x0b\x65xchange_id\x18\x01 \x03(\x03R\nexchangeId\"m\n\x1bGetIndexPriceConfigResponse\x12N\n\x0cprice_config\x18\x01 \x03(\x0b\x32+.antx.server.price.ExchangeIndexPriceConfigR\x0bpriceConfig\"\x8b\x01\n\x18\x45xchangeIndexPriceConfig\x12\x1f\n\x0b\x65xchange_id\x18\x01 \x01(\x03R\nexchangeId\x12N\n\rexchange_info\x18\x02 \x03(\x0b\x32).antx.server.price.IndexPriceExchangeInfoR\x0c\x65xchangeInfo\"|\n\x16IndexPriceExchangeInfo\x12#\n\rexchange_name\x18\x01 \x01(\tR\x0c\x65xchangeName\x12%\n\x0e\x65xchange_quote\x18\x02 \x01(\tR\rexchangeQuote\x12\x16\n\x06weight\x18\x03 \x01(\tR\x06weight\"\x8a\x01\n\x15\x46orcePushPriceRequest\x12\x1f\n\x0b\x65xchange_id\x18\x01 \x01(\x03R\nexchangeId\x12:\n\nprice_type\x18\x02 \x01(\x0e\x32\x1b.antx.chain.price.PriceTypeR\tpriceType\x12\x14\n\x05price\x18\x03 \x01(\tR\x05price\"\x18\n\x16\x46orcePushPriceResponse\"\x1a\n\x18GetFlatTokenPriceRequest\"g\n\x19GetFlatTokenPriceResponse\x12$\n\x0eusdc_usd_price\x18\x01 \x01(\tR\x0cusdcUsdPrice\x12$\n\x0eusdt_usd_price\x18\x02 \x01(\tR\x0cusdtUsdPrice2\xdb\x02\n\x0cPriceService\x12t\n\x13GetIndexPriceConfig\x12-.antx.server.price.GetIndexPriceConfigRequest\x1a..antx.server.price.GetIndexPriceConfigResponse\x12\x65\n\x0e\x46orcePushPrice\x12(.antx.server.price.ForcePushPriceRequest\x1a).antx.server.price.ForcePushPriceResponse\x12n\n\x11GetFlatTokenPrice\x12+.antx.server.price.GetFlatTokenPriceRequest\x1a,.antx.server.price.GetFlatTokenPriceResponseB3\n exchange.antx.proto.server.priceB\rPriceRpcProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antx.server.price.price_rpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n exchange.antx.proto.server.priceB\rPriceRpcProtoP\001'
  _globals['_GETINDEXPRICECONFIGREQUEST']._serialized_start=86
  _globals['_GETINDEXPRICECONFIGREQUEST']._serialized_end=147
  _globals['_GETINDEXPRICECONFIGRESPONSE']._serialized_start=149
  _globals['_GETINDEXPRICECONFIGRESPONSE']._serialized_end=258
  _globals['_EXCHANGEINDEXPRICECONFIG']._serialized_start=261
  _globals['_EXCHANGEINDEXPRICECONFIG']._serialized_end=400
  _globals['_INDEXPRICEEXCHANGEINFO']._serialized_start=402
  _globals['_INDEXPRICEEXCHANGEINFO']._serialized_end=526
  _globals['_FORCEPUSHPRICEREQUEST']._serialized_start=529
  _globals['_FORCEPUSHPRICEREQUEST']._serialized_end=667
  _globals['_FORCEPUSHPRICERESPONSE']._serialized_start=669
  _globals['_FORCEPUSHPRICERESPONSE']._serialized_end=693
  _globals['_GETFLATTOKENPRICEREQUEST']._serialized_start=695
  _globals['_GETFLATTOKENPRICEREQUEST']._serialized_end=721
  _globals['_GETFLATTOKENPRICERESPONSE']._serialized_start=723
  _globals['_GETFLATTOKENPRICERESPONSE']._serialized_end=826
  _globals['_PRICESERVICE']._serialized_start=829
  _globals['_PRICESERVICE']._serialized_end=1176
# @@protoc_insertion_point(module_scope)
