# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from antx.server.faucet import faucet_rpc_pb2 as antx_dot_server_dot_faucet_dot_faucet__rpc__pb2


class FaucetServiceStub(object):
    """水龙头 服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFaucet = channel.unary_unary(
                '/antx.server.faucet.FaucetService/GetFaucet',
                request_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetFaucetRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetFaucetResponse.FromString,
                _registered_method=True)
        self.UpdateFaucet = channel.unary_unary(
                '/antx.server.faucet.FaucetService/UpdateFaucet',
                request_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.UpdateFaucetRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.UpdateFaucetResponse.FromString,
                _registered_method=True)
        self.Claim = channel.unary_unary(
                '/antx.server.faucet.FaucetService/Claim',
                request_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.ClaimRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.ClaimResponse.FromString,
                _registered_method=True)
        self.SendGift = channel.unary_unary(
                '/antx.server.faucet.FaucetService/SendGift',
                request_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.SendGiftRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.SendGiftResponse.FromString,
                _registered_method=True)
        self.GenerateInviteCode = channel.unary_unary(
                '/antx.server.faucet.FaucetService/GenerateInviteCode',
                request_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GenerateInviteCodeRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GenerateInviteCodeResponse.FromString,
                _registered_method=True)
        self.GetInviteCodeList = channel.unary_unary(
                '/antx.server.faucet.FaucetService/GetInviteCodeList',
                request_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetInviteCodeListRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetInviteCodeListResponse.FromString,
                _registered_method=True)
        self.UpdateInviteCodeExpireTime = channel.unary_unary(
                '/antx.server.faucet.FaucetService/UpdateInviteCodeExpireTime',
                request_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.UpdateInviteCodeExpireTimeRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.UpdateInviteCodeExpireTimeResponse.FromString,
                _registered_method=True)
        self.BindInviteCode = channel.unary_unary(
                '/antx.server.faucet.FaucetService/BindInviteCode',
                request_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.BindInviteCodeRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.BindInviteCodeResponse.FromString,
                _registered_method=True)
        self.IsBindInviteCode = channel.unary_unary(
                '/antx.server.faucet.FaucetService/IsBindInviteCode',
                request_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.IsBindInviteCodeRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.IsBindInviteCodeResponse.FromString,
                _registered_method=True)
        self.GetBonusRecordList = channel.unary_unary(
                '/antx.server.faucet.FaucetService/GetBonusRecordList',
                request_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetBonusRecordListRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetBonusRecordListResponse.FromString,
                _registered_method=True)


class FaucetServiceServicer(object):
    """水龙头 服务
    """

    def GetFaucet(self, request, context):
        """获取领水限制
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFaucet(self, request, context):
        """更新领水限制
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Claim(self, request, context):
        """领水
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendGift(self, request, context):
        """赠金
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateInviteCode(self, request, context):
        """生成邀请码
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInviteCodeList(self, request, context):
        """获取邀请码列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInviteCodeExpireTime(self, request, context):
        """更新邀请码
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BindInviteCode(self, request, context):
        """用户绑定邀请码
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsBindInviteCode(self, request, context):
        """查询用户是否绑定邀请码
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBonusRecordList(self, request, context):
        """获取赠金记录列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaucetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFaucet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFaucet,
                    request_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetFaucetRequest.FromString,
                    response_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetFaucetResponse.SerializeToString,
            ),
            'UpdateFaucet': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFaucet,
                    request_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.UpdateFaucetRequest.FromString,
                    response_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.UpdateFaucetResponse.SerializeToString,
            ),
            'Claim': grpc.unary_unary_rpc_method_handler(
                    servicer.Claim,
                    request_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.ClaimRequest.FromString,
                    response_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.ClaimResponse.SerializeToString,
            ),
            'SendGift': grpc.unary_unary_rpc_method_handler(
                    servicer.SendGift,
                    request_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.SendGiftRequest.FromString,
                    response_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.SendGiftResponse.SerializeToString,
            ),
            'GenerateInviteCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateInviteCode,
                    request_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GenerateInviteCodeRequest.FromString,
                    response_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GenerateInviteCodeResponse.SerializeToString,
            ),
            'GetInviteCodeList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInviteCodeList,
                    request_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetInviteCodeListRequest.FromString,
                    response_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetInviteCodeListResponse.SerializeToString,
            ),
            'UpdateInviteCodeExpireTime': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInviteCodeExpireTime,
                    request_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.UpdateInviteCodeExpireTimeRequest.FromString,
                    response_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.UpdateInviteCodeExpireTimeResponse.SerializeToString,
            ),
            'BindInviteCode': grpc.unary_unary_rpc_method_handler(
                    servicer.BindInviteCode,
                    request_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.BindInviteCodeRequest.FromString,
                    response_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.BindInviteCodeResponse.SerializeToString,
            ),
            'IsBindInviteCode': grpc.unary_unary_rpc_method_handler(
                    servicer.IsBindInviteCode,
                    request_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.IsBindInviteCodeRequest.FromString,
                    response_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.IsBindInviteCodeResponse.SerializeToString,
            ),
            'GetBonusRecordList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBonusRecordList,
                    request_deserializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetBonusRecordListRequest.FromString,
                    response_serializer=antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetBonusRecordListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antx.server.faucet.FaucetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antx.server.faucet.FaucetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaucetService(object):
    """水龙头 服务
    """

    @staticmethod
    def GetFaucet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.faucet.FaucetService/GetFaucet',
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetFaucetRequest.SerializeToString,
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetFaucetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFaucet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.faucet.FaucetService/UpdateFaucet',
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.UpdateFaucetRequest.SerializeToString,
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.UpdateFaucetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Claim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.faucet.FaucetService/Claim',
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.ClaimRequest.SerializeToString,
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.ClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendGift(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.faucet.FaucetService/SendGift',
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.SendGiftRequest.SerializeToString,
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.SendGiftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateInviteCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.faucet.FaucetService/GenerateInviteCode',
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GenerateInviteCodeRequest.SerializeToString,
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GenerateInviteCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInviteCodeList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.faucet.FaucetService/GetInviteCodeList',
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetInviteCodeListRequest.SerializeToString,
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetInviteCodeListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInviteCodeExpireTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.faucet.FaucetService/UpdateInviteCodeExpireTime',
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.UpdateInviteCodeExpireTimeRequest.SerializeToString,
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.UpdateInviteCodeExpireTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BindInviteCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.faucet.FaucetService/BindInviteCode',
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.BindInviteCodeRequest.SerializeToString,
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.BindInviteCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsBindInviteCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.faucet.FaucetService/IsBindInviteCode',
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.IsBindInviteCodeRequest.SerializeToString,
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.IsBindInviteCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBonusRecordList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.faucet.FaucetService/GetBonusRecordList',
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetBonusRecordListRequest.SerializeToString,
            antx_dot_server_dot_faucet_dot_faucet__rpc__pb2.GetBonusRecordListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
