# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from antx.chain.offchain import query_pb2 as antx_dot_chain_dot_offchain_dot_query__pb2


class QueryStub(object):
    """Query defines the gRPC querier service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Params = channel.unary_unary(
                '/antx.chain.offchain.Query/Params',
                request_serializer=antx_dot_chain_dot_offchain_dot_query__pb2.QueryParamsRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_offchain_dot_query__pb2.QueryParamsResponse.FromString,
                _registered_method=True)
        self.GetEventSequence = channel.unary_unary(
                '/antx.chain.offchain.Query/GetEventSequence',
                request_serializer=antx_dot_chain_dot_offchain_dot_query__pb2.QueryGetEventSequenceRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_offchain_dot_query__pb2.QueryGetEventSequenceResponse.FromString,
                _registered_method=True)
        self.OffchainEventStream = channel.unary_stream(
                '/antx.chain.offchain.Query/OffchainEventStream',
                request_serializer=antx_dot_chain_dot_offchain_dot_query__pb2.QueryOffchainEventStreamRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_offchain_dot_query__pb2.QueryOffchainEventStreamResponse.FromString,
                _registered_method=True)


class QueryServicer(object):
    """Query defines the gRPC querier service.
    """

    def Params(self, request, context):
        """Parameters queries the parameters of the module.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEventSequence(self, request, context):
        """获取事件序号
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OffchainEventStream(self, request, context):
        """获取offchain事件流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Params': grpc.unary_unary_rpc_method_handler(
                    servicer.Params,
                    request_deserializer=antx_dot_chain_dot_offchain_dot_query__pb2.QueryParamsRequest.FromString,
                    response_serializer=antx_dot_chain_dot_offchain_dot_query__pb2.QueryParamsResponse.SerializeToString,
            ),
            'GetEventSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEventSequence,
                    request_deserializer=antx_dot_chain_dot_offchain_dot_query__pb2.QueryGetEventSequenceRequest.FromString,
                    response_serializer=antx_dot_chain_dot_offchain_dot_query__pb2.QueryGetEventSequenceResponse.SerializeToString,
            ),
            'OffchainEventStream': grpc.unary_stream_rpc_method_handler(
                    servicer.OffchainEventStream,
                    request_deserializer=antx_dot_chain_dot_offchain_dot_query__pb2.QueryOffchainEventStreamRequest.FromString,
                    response_serializer=antx_dot_chain_dot_offchain_dot_query__pb2.QueryOffchainEventStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antx.chain.offchain.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antx.chain.offchain.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Query defines the gRPC querier service.
    """

    @staticmethod
    def Params(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.offchain.Query/Params',
            antx_dot_chain_dot_offchain_dot_query__pb2.QueryParamsRequest.SerializeToString,
            antx_dot_chain_dot_offchain_dot_query__pb2.QueryParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEventSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.offchain.Query/GetEventSequence',
            antx_dot_chain_dot_offchain_dot_query__pb2.QueryGetEventSequenceRequest.SerializeToString,
            antx_dot_chain_dot_offchain_dot_query__pb2.QueryGetEventSequenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OffchainEventStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/antx.chain.offchain.Query/OffchainEventStream',
            antx_dot_chain_dot_offchain_dot_query__pb2.QueryOffchainEventStreamRequest.SerializeToString,
            antx_dot_chain_dot_offchain_dot_query__pb2.QueryOffchainEventStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
