# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antx/chain/offchain/query.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from antx.chain.offchain import offchain_pb2 as antx_dot_chain_dot_offchain_dot_offchain__pb2
from antx.chain.offchain import params_pb2 as antx_dot_chain_dot_offchain_dot_params__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61ntx/chain/offchain/query.proto\x12\x13\x61ntx.chain.offchain\x1a\x11\x61mino/amino.proto\x1a\"antx/chain/offchain/offchain.proto\x1a antx/chain/offchain/params.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\"\x14\n\x12QueryParamsRequest\"U\n\x13QueryParamsResponse\x12>\n\x06params\x18\x01 \x01(\x0b\x32\x1b.antx.chain.offchain.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\"\x1e\n\x1cQueryGetEventSequenceRequest\"F\n\x1dQueryGetEventSequenceResponse\x12%\n\x0e\x65vent_sequence\x18\x01 \x01(\x04R\reventSequence\"!\n\x1fQueryOffchainEventStreamRequest\"m\n QueryOffchainEventStreamResponse\x12I\n\x0eoffchain_event\x18\x01 \x03(\x0b\x32\".antx.chain.offchain.OffchainEventR\roffchainEvent2\x85\x03\n\x05Query\x12z\n\x06Params\x12\'.antx.chain.offchain.QueryParamsRequest\x1a(.antx.chain.offchain.QueryParamsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/antx/offchain/params\x12y\n\x10GetEventSequence\x12\x31.antx.chain.offchain.QueryGetEventSequenceRequest\x1a\x32.antx.chain.offchain.QueryGetEventSequenceResponse\x12\x84\x01\n\x13OffchainEventStream\x12\x34.antx.chain.offchain.QueryOffchainEventStreamRequest\x1a\x35.antx.chain.offchain.QueryOffchainEventStreamResponse0\x01\x42\x65\n\"exchange.antx.proto.chain.offchainB\nQueryProtoP\x01Z-github.com/antxprotocol/antx/x/offchain/types\xf0\xe1\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antx.chain.offchain.query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"exchange.antx.proto.chain.offchainB\nQueryProtoP\001Z-github.com/antxprotocol/antx/x/offchain/types\360\341\036\001'
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._options = None
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_QUERY'].methods_by_name['Params']._options = None
  _globals['_QUERY'].methods_by_name['Params']._serialized_options = b'\202\323\344\223\002\027\022\025/antx/offchain/params'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=197
  _globals['_QUERYPARAMSREQUEST']._serialized_end=217
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=219
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=304
  _globals['_QUERYGETEVENTSEQUENCEREQUEST']._serialized_start=306
  _globals['_QUERYGETEVENTSEQUENCEREQUEST']._serialized_end=336
  _globals['_QUERYGETEVENTSEQUENCERESPONSE']._serialized_start=338
  _globals['_QUERYGETEVENTSEQUENCERESPONSE']._serialized_end=408
  _globals['_QUERYOFFCHAINEVENTSTREAMREQUEST']._serialized_start=410
  _globals['_QUERYOFFCHAINEVENTSTREAMREQUEST']._serialized_end=443
  _globals['_QUERYOFFCHAINEVENTSTREAMRESPONSE']._serialized_start=445
  _globals['_QUERYOFFCHAINEVENTSTREAMRESPONSE']._serialized_end=554
  _globals['_QUERY']._serialized_start=557
  _globals['_QUERY']._serialized_end=946
# @@protoc_insertion_point(module_scope)
