# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antex/server/stats/stats_type.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'antex/server/stats/stats_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antex_proto.antex.chain.price import price_pb2 as antex_dot_chain_dot_price_dot_price__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#antex/server/stats/stats_type.proto\x12\x12\x61ntex.server.stats\x1a\x1d\x61ntex/chain/price/price.proto\"\x8c\x01\n\x0cStatsSummary\x12<\n\nstats_type\x18\x01 \x01(\x0e\x32\x1d.antex.server.stats.StatsTypeR\tstatsType\x12\x1d\n\nstats_time\x18\x02 \x01(\x04R\tstatsTime\x12\x1f\n\x0bstats_value\x18\x03 \x01(\tR\nstatsValue\"\xd9\x02\n\x11TotalStatsSummary\x12\x1f\n\x0b\x65xchange_id\x18\x01 \x01(\x04R\nexchangeId\x12?\n\ntotal_user\x18\x02 \x01(\x0b\x32 .antex.server.stats.StatsSummaryR\ttotalUser\x12\x41\n\x0btotal_trade\x18\x03 \x01(\x0b\x32 .antex.server.stats.StatsSummaryR\ntotalTrade\x12P\n\x13total_open_interest\x18\x04 \x01(\x0b\x32 .antex.server.stats.StatsSummaryR\x11totalOpenInterest\x12M\n\x11total_liquidation\x18\x05 \x01(\x0b\x32 .antex.server.stats.StatsSummaryR\x10totalLiquidation*\xb8\x02\n\tStatsType\x12\x1a\n\x16STATS_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15STATS_TYPE_TOTAL_USER\x10\x01\x12\x1a\n\x16STATS_TYPE_TOTAL_TRADE\x10\x02\x12#\n\x1fSTATS_TYPE_EXCHANGE_TOTAL_TRADE\x10\x03\x12!\n\x1dSTATS_TYPE_EXCHANGE_DAY_TRADE\x10\x04\x12\"\n\x1eSTATS_TYPE_TOTAL_OPEN_INTEREST\x10\x05\x12%\n!STATS_TYPE_EXCHANGE_OPEN_INTEREST\x10\x06\x12 \n\x1cSTATS_TYPE_TOTAL_LIQUIDATION\x10\x07\x12#\n\x1fSTATS_TYPE_EXCHANGE_LIQUIDATION\x10\x08\x42\x35\n!exchange.antex.proto.server.statsB\x0eStatsTypeProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antex.server.stats.stats_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!exchange.antex.proto.server.statsB\016StatsTypeProtoP\001'
  _globals['_STATSTYPE']._serialized_start=582
  _globals['_STATSTYPE']._serialized_end=894
  _globals['_STATSSUMMARY']._serialized_start=91
  _globals['_STATSSUMMARY']._serialized_end=231
  _globals['_TOTALSTATSSUMMARY']._serialized_start=234
  _globals['_TOTALSTATSSUMMARY']._serialized_end=579
# @@protoc_insertion_point(module_scope)
