# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from antx.chain.price import query_pb2 as antx_dot_chain_dot_price_dot_query__pb2


class QueryStub(object):
    """Query defines the gRPC querier service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Params = channel.unary_unary(
                '/antx.chain.price.Query/Params',
                request_serializer=antx_dot_chain_dot_price_dot_query__pb2.QueryParamsRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_price_dot_query__pb2.QueryParamsResponse.FromString,
                _registered_method=True)
        self.GetPriceTick = channel.unary_unary(
                '/antx.chain.price.Query/GetPriceTick',
                request_serializer=antx_dot_chain_dot_price_dot_query__pb2.QueryGetPriceTickRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_price_dot_query__pb2.QueryGetPriceTickResponse.FromString,
                _registered_method=True)
        self.ListPriceTick = channel.unary_unary(
                '/antx.chain.price.Query/ListPriceTick',
                request_serializer=antx_dot_chain_dot_price_dot_query__pb2.QueryListPriceTickRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_price_dot_query__pb2.QueryListPriceTickResponse.FromString,
                _registered_method=True)


class QueryServicer(object):
    """Query defines the gRPC querier service.
    """

    def Params(self, request, context):
        """Parameters queries the parameters of the module.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPriceTick(self, request, context):
        """根据exchangeId查询priceTick信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPriceTick(self, request, context):
        """翻页查询查询priceTick信息列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Params': grpc.unary_unary_rpc_method_handler(
                    servicer.Params,
                    request_deserializer=antx_dot_chain_dot_price_dot_query__pb2.QueryParamsRequest.FromString,
                    response_serializer=antx_dot_chain_dot_price_dot_query__pb2.QueryParamsResponse.SerializeToString,
            ),
            'GetPriceTick': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPriceTick,
                    request_deserializer=antx_dot_chain_dot_price_dot_query__pb2.QueryGetPriceTickRequest.FromString,
                    response_serializer=antx_dot_chain_dot_price_dot_query__pb2.QueryGetPriceTickResponse.SerializeToString,
            ),
            'ListPriceTick': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPriceTick,
                    request_deserializer=antx_dot_chain_dot_price_dot_query__pb2.QueryListPriceTickRequest.FromString,
                    response_serializer=antx_dot_chain_dot_price_dot_query__pb2.QueryListPriceTickResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antx.chain.price.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antx.chain.price.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Query defines the gRPC querier service.
    """

    @staticmethod
    def Params(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.price.Query/Params',
            antx_dot_chain_dot_price_dot_query__pb2.QueryParamsRequest.SerializeToString,
            antx_dot_chain_dot_price_dot_query__pb2.QueryParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPriceTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.price.Query/GetPriceTick',
            antx_dot_chain_dot_price_dot_query__pb2.QueryGetPriceTickRequest.SerializeToString,
            antx_dot_chain_dot_price_dot_query__pb2.QueryGetPriceTickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPriceTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.price.Query/ListPriceTick',
            antx_dot_chain_dot_price_dot_query__pb2.QueryListPriceTickRequest.SerializeToString,
            antx_dot_chain_dot_price_dot_query__pb2.QueryListPriceTickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
