# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from antx.server.vault import vault_rpc_pb2 as antx_dot_server_dot_vault_dot_vault__rpc__pb2


class VaultServiceStub(object):
    """金库服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListVault = channel.unary_unary(
                '/antx.server.vault.VaultService/ListVault',
                request_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultResponse.FromString,
                _registered_method=True)
        self.ListVaultSnapshot = channel.unary_unary(
                '/antx.server.vault.VaultService/ListVaultSnapshot',
                request_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultSnapshotRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultSnapshotResponse.FromString,
                _registered_method=True)
        self.ListVaultAction = channel.unary_unary(
                '/antx.server.vault.VaultService/ListVaultAction',
                request_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultActionRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultActionResponse.FromString,
                _registered_method=True)
        self.ListOwnerShare = channel.unary_unary(
                '/antx.server.vault.VaultService/ListOwnerShare',
                request_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListOwnerShareRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListOwnerShareResponse.FromString,
                _registered_method=True)
        self.GetUserOwnerShare = channel.unary_unary(
                '/antx.server.vault.VaultService/GetUserOwnerShare',
                request_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.GetUserOwnerShareRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.GetUserOwnerShareResponse.FromString,
                _registered_method=True)
        self.GetVaultById = channel.unary_unary(
                '/antx.server.vault.VaultService/GetVaultById',
                request_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.GetVaultByIdRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.GetVaultByIdResponse.FromString,
                _registered_method=True)
        self.ListVaultMaker = channel.unary_unary(
                '/antx.server.vault.VaultService/ListVaultMaker',
                request_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultMakerRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultMakerResponse.FromString,
                _registered_method=True)
        self.AddVaultMaker = channel.unary_unary(
                '/antx.server.vault.VaultService/AddVaultMaker',
                request_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.AddVaultMakerRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.AddVaultMakerResponse.FromString,
                _registered_method=True)
        self.DelVaultMaker = channel.unary_unary(
                '/antx.server.vault.VaultService/DelVaultMaker',
                request_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.DelVaultMakerRequest.SerializeToString,
                response_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.DelVaultMakerResponse.FromString,
                _registered_method=True)


class VaultServiceServicer(object):
    """金库服务
    """

    def ListVault(self, request, context):
        """List vault.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVaultSnapshot(self, request, context):
        """List vault snapshots.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVaultAction(self, request, context):
        """List vault action for a vault.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOwnerShare(self, request, context):
        """Returns share & equity information for a single vault.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserOwnerShare(self, request, context):
        """Returns share & unlock
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVaultById(self, request, context):
        """Returns vault info.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVaultMaker(self, request, context):
        """//////////////// admin //////////////////
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddVaultMaker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DelVaultMaker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VaultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListVault': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVault,
                    request_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultRequest.FromString,
                    response_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultResponse.SerializeToString,
            ),
            'ListVaultSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVaultSnapshot,
                    request_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultSnapshotRequest.FromString,
                    response_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultSnapshotResponse.SerializeToString,
            ),
            'ListVaultAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVaultAction,
                    request_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultActionRequest.FromString,
                    response_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultActionResponse.SerializeToString,
            ),
            'ListOwnerShare': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOwnerShare,
                    request_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListOwnerShareRequest.FromString,
                    response_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListOwnerShareResponse.SerializeToString,
            ),
            'GetUserOwnerShare': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserOwnerShare,
                    request_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.GetUserOwnerShareRequest.FromString,
                    response_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.GetUserOwnerShareResponse.SerializeToString,
            ),
            'GetVaultById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVaultById,
                    request_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.GetVaultByIdRequest.FromString,
                    response_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.GetVaultByIdResponse.SerializeToString,
            ),
            'ListVaultMaker': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVaultMaker,
                    request_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultMakerRequest.FromString,
                    response_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultMakerResponse.SerializeToString,
            ),
            'AddVaultMaker': grpc.unary_unary_rpc_method_handler(
                    servicer.AddVaultMaker,
                    request_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.AddVaultMakerRequest.FromString,
                    response_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.AddVaultMakerResponse.SerializeToString,
            ),
            'DelVaultMaker': grpc.unary_unary_rpc_method_handler(
                    servicer.DelVaultMaker,
                    request_deserializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.DelVaultMakerRequest.FromString,
                    response_serializer=antx_dot_server_dot_vault_dot_vault__rpc__pb2.DelVaultMakerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antx.server.vault.VaultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antx.server.vault.VaultService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VaultService(object):
    """金库服务
    """

    @staticmethod
    def ListVault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.vault.VaultService/ListVault',
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultRequest.SerializeToString,
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVaultSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.vault.VaultService/ListVaultSnapshot',
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultSnapshotRequest.SerializeToString,
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVaultAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.vault.VaultService/ListVaultAction',
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultActionRequest.SerializeToString,
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOwnerShare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.vault.VaultService/ListOwnerShare',
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListOwnerShareRequest.SerializeToString,
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListOwnerShareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserOwnerShare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.vault.VaultService/GetUserOwnerShare',
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.GetUserOwnerShareRequest.SerializeToString,
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.GetUserOwnerShareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVaultById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.vault.VaultService/GetVaultById',
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.GetVaultByIdRequest.SerializeToString,
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.GetVaultByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVaultMaker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.vault.VaultService/ListVaultMaker',
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultMakerRequest.SerializeToString,
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.ListVaultMakerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddVaultMaker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.vault.VaultService/AddVaultMaker',
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.AddVaultMakerRequest.SerializeToString,
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.AddVaultMakerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DelVaultMaker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.server.vault.VaultService/DelVaultMaker',
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.DelVaultMakerRequest.SerializeToString,
            antx_dot_server_dot_vault_dot_vault__rpc__pb2.DelVaultMakerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
