# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antex/chain/price/query.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'antex/chain/price/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antex_proto.amino import amino_pb2 as amino_dot_amino__pb2
from antex_proto.antex.chain.price import params_pb2 as antex_dot_chain_dot_price_dot_params__pb2
from antex_proto.antex.chain.price import price_pb2 as antex_dot_chain_dot_price_dot_price__pb2
from antex_proto.cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from antex_proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61ntex/chain/price/query.proto\x12\x11\x61ntex.chain.price\x1a\x11\x61mino/amino.proto\x1a\x1e\x61ntex/chain/price/params.proto\x1a\x1d\x61ntex/chain/price/price.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\"\x14\n\x12QueryParamsRequest\"S\n\x13QueryParamsResponse\x12<\n\x06params\x18\x01 \x01(\x0b\x32\x19.antex.chain.price.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\"x\n\x18QueryGetPriceTickRequest\x12;\n\nprice_type\x18\x01 \x01(\x0e\x32\x1c.antex.chain.price.PriceTypeR\tpriceType\x12\x1f\n\x0b\x65xchange_id\x18\x02 \x03(\x04R\nexchangeId\"X\n\x19QueryGetPriceTickResponse\x12;\n\nprice_tick\x18\x01 \x03(\x0b\x32\x1c.antex.chain.price.PriceTickR\tpriceTick\"\xa0\x01\n\x19QueryListPriceTickRequest\x12;\n\nprice_type\x18\x01 \x01(\x0e\x32\x1c.antex.chain.price.PriceTypeR\tpriceType\x12\x46\n\npagination\x18\x02 \x01(\x0b\x32&.cosmos.base.query.v1beta1.PageRequestR\npagination\"\xa2\x01\n\x1aQueryListPriceTickResponse\x12;\n\nprice_tick\x18\x01 \x03(\x0b\x32\x1c.antex.chain.price.PriceTickR\tpriceTick\x12G\n\npagination\x18\x02 \x01(\x0b\x32\'.cosmos.base.query.v1beta1.PageResponseR\npagination2\xcb\x03\n\x05Query\x12t\n\x06Params\x12%.antex.chain.price.QueryParamsRequest\x1a&.antex.chain.price.QueryParamsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/antex/price/params\x12\xa9\x01\n\x0cGetPriceTick\x12+.antex.chain.price.QueryGetPriceTickRequest\x1a,.antex.chain.price.QueryGetPriceTickResponse\">\x82\xd3\xe4\x93\x02\x38\x12\x36/antex/price/get_price_tick/{price_type}/{exchange_id}\x12\x9f\x01\n\rListPriceTick\x12,.antex.chain.price.QueryListPriceTickRequest\x1a-.antex.chain.price.QueryListPriceTickResponse\"1\x82\xd3\xe4\x93\x02+\x12)/antex/price/list_price_tick/{price_type}Bb\n exchange.antex.proto.chain.priceB\nQueryProtoP\x01Z,github.com/antexprotocol/antex/x/price/types\xf0\xe1\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antex.chain.price.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n exchange.antex.proto.chain.priceB\nQueryProtoP\001Z,github.com/antexprotocol/antex/x/price/types\360\341\036\001'
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._loaded_options = None
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_QUERY'].methods_by_name['Params']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Params']._serialized_options = b'\202\323\344\223\002\025\022\023/antex/price/params'
  _globals['_QUERY'].methods_by_name['GetPriceTick']._loaded_options = None
  _globals['_QUERY'].methods_by_name['GetPriceTick']._serialized_options = b'\202\323\344\223\0028\0226/antex/price/get_price_tick/{price_type}/{exchange_id}'
  _globals['_QUERY'].methods_by_name['ListPriceTick']._loaded_options = None
  _globals['_QUERY'].methods_by_name['ListPriceTick']._serialized_options = b'\202\323\344\223\002+\022)/antex/price/list_price_tick/{price_type}'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=230
  _globals['_QUERYPARAMSREQUEST']._serialized_end=250
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=252
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=335
  _globals['_QUERYGETPRICETICKREQUEST']._serialized_start=337
  _globals['_QUERYGETPRICETICKREQUEST']._serialized_end=457
  _globals['_QUERYGETPRICETICKRESPONSE']._serialized_start=459
  _globals['_QUERYGETPRICETICKRESPONSE']._serialized_end=547
  _globals['_QUERYLISTPRICETICKREQUEST']._serialized_start=550
  _globals['_QUERYLISTPRICETICKREQUEST']._serialized_end=710
  _globals['_QUERYLISTPRICETICKRESPONSE']._serialized_start=713
  _globals['_QUERYLISTPRICETICKRESPONSE']._serialized_end=875
  _globals['_QUERY']._serialized_start=878
  _globals['_QUERY']._serialized_end=1337
# @@protoc_insertion_point(module_scope)
