# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antex/chain/price/tx.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'antex/chain/price/tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antex_proto.amino import amino_pb2 as amino_dot_amino__pb2
from antex_proto.antex.chain.price import params_pb2 as antex_dot_chain_dot_price_dot_params__pb2
from antex_proto.antex.chain.price import price_pb2 as antex_dot_chain_dot_price_dot_price__pb2
from antex_proto.cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from antex_proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from antex_proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61ntex/chain/price/tx.proto\x12\x11\x61ntex.chain.price\x1a\x11\x61mino/amino.proto\x1a\x1e\x61ntex/chain/price/params.proto\x1a\x1d\x61ntex/chain/price/price.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\"\xb9\x01\n\x0fMsgUpdateParams\x12\x36\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\tauthority\x12<\n\x06params\x18\x02 \x01(\x0b\x32\x19.antex.chain.price.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params:0\x82\xe7\xb0*\tauthority\x8a\xe7\xb0*\x1d\x61ntex/x/price/MsgUpdateParams\"\x19\n\x17MsgUpdateParamsResponse\"\xd8\x01\n\x13UpdatePriceTickItem\x12\x1f\n\x0b\x65xchange_id\x18\x01 \x01(\x04R\nexchangeId\x12;\n\nprice_type\x18\x02 \x01(\x0e\x32\x1c.antex.chain.price.PriceTypeR\tpriceType\x12\x1f\n\x0bprice_scale\x18\x03 \x01(\x11R\npriceScale\x12\x1f\n\x0bprice_value\x18\x04 \x01(\x04R\npriceValue\x12!\n\x0c\x63reated_time\x18\x05 \x01(\x04R\x0b\x63reatedTime\"\xe9\x01\n\x12MsgUpdatePriceTick\x12=\n\rowner_address\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x0cownerAddress\x12[\n\x16update_price_tick_item\x18\x02 \x03(\x0b\x32&.antex.chain.price.UpdatePriceTickItemR\x13updatePriceTickItem:7\x82\xe7\xb0*\rowner_address\x8a\xe7\xb0* antex/x/price/MsgUpdatePriceTick\"\x1c\n\x1aMsgUpdatePriceTickResponse2\xd5\x01\n\x03Msg\x12^\n\x0cUpdateParams\x12\".antex.chain.price.MsgUpdateParams\x1a*.antex.chain.price.MsgUpdateParamsResponse\x12g\n\x0fUpdatePriceTick\x12%.antex.chain.price.MsgUpdatePriceTick\x1a-.antex.chain.price.MsgUpdatePriceTickResponse\x1a\x05\x80\xe7\xb0*\x01\x42_\n exchange.antex.proto.chain.priceB\x07TxProtoP\x01Z,github.com/antexprotocol/antex/x/price/types\xf0\xe1\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antex.chain.price.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n exchange.antex.proto.chain.priceB\007TxProtoP\001Z,github.com/antexprotocol/antex/x/price/types\360\341\036\001'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['authority']._loaded_options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['authority']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._loaded_options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_MSGUPDATEPARAMS']._loaded_options = None
  _globals['_MSGUPDATEPARAMS']._serialized_options = b'\202\347\260*\tauthority\212\347\260*\035antex/x/price/MsgUpdateParams'
  _globals['_MSGUPDATEPRICETICK'].fields_by_name['owner_address']._loaded_options = None
  _globals['_MSGUPDATEPRICETICK'].fields_by_name['owner_address']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGUPDATEPRICETICK']._loaded_options = None
  _globals['_MSGUPDATEPRICETICK']._serialized_options = b'\202\347\260*\rowner_address\212\347\260* antex/x/price/MsgUpdatePriceTick'
  _globals['_MSG']._loaded_options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSGUPDATEPARAMS']._serialized_start=206
  _globals['_MSGUPDATEPARAMS']._serialized_end=391
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_start=393
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_end=418
  _globals['_UPDATEPRICETICKITEM']._serialized_start=421
  _globals['_UPDATEPRICETICKITEM']._serialized_end=637
  _globals['_MSGUPDATEPRICETICK']._serialized_start=640
  _globals['_MSGUPDATEPRICETICK']._serialized_end=873
  _globals['_MSGUPDATEPRICETICKRESPONSE']._serialized_start=875
  _globals['_MSGUPDATEPRICETICKRESPONSE']._serialized_end=903
  _globals['_MSG']._serialized_start=906
  _globals['_MSG']._serialized_end=1119
# @@protoc_insertion_point(module_scope)
