# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antex/chain/asset/params.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'antex/chain/asset/params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antex_proto.amino import amino_pb2 as amino_dot_amino__pb2
from antex_proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61ntex/chain/asset/params.proto\x12\x11\x61ntex.chain.asset\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\"\xbb\x02\n\x06Params\x12#\n\rowner_address\x18\x01 \x03(\tR\x0cownerAddress\x12&\n\x0fsystem_chain_id\x18\x02 \x01(\x04R\rsystemChainId\x12.\n\x13system_coin_address\x18\x03 \x01(\tR\x11systemCoinAddress\x12\x31\n\x15system_sub_account_id\x18\x04 \x01(\x04R\x12systemSubAccountId\x12\x30\n\x14system_coin_decimals\x18\x05 \x01(\rR\x12systemCoinDecimals\x12\x30\n\x14system_asset_address\x18\x06 \x01(\tR\x12systemAssetAddress:\x1d\xe8\xa0\x1f\x01\x8a\xe7\xb0*\x14\x61ntex/x/asset/ParamsBc\n exchange.antex.proto.chain.assetB\x0bParamsProtoP\x01Z,github.com/antexprotocol/antex/x/asset/types\xf0\xe1\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antex.chain.asset.params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n exchange.antex.proto.chain.assetB\013ParamsProtoP\001Z,github.com/antexprotocol/antex/x/asset/types\360\341\036\001'
  _globals['_PARAMS']._loaded_options = None
  _globals['_PARAMS']._serialized_options = b'\350\240\037\001\212\347\260*\024antex/x/asset/Params'
  _globals['_PARAMS']._serialized_start=95
  _globals['_PARAMS']._serialized_end=410
# @@protoc_insertion_point(module_scope)
