# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from antx.chain.exchange import query_pb2 as antx_dot_chain_dot_exchange_dot_query__pb2


class QueryStub(object):
    """Query defines the gRPC querier service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Params = channel.unary_unary(
                '/antx.chain.exchange.Query/Params',
                request_serializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryParamsRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryParamsResponse.FromString,
                _registered_method=True)
        self.GetCoin = channel.unary_unary(
                '/antx.chain.exchange.Query/GetCoin',
                request_serializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetCoinRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetCoinResponse.FromString,
                _registered_method=True)
        self.ListCoin = channel.unary_unary(
                '/antx.chain.exchange.Query/ListCoin',
                request_serializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryListCoinRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryListCoinResponse.FromString,
                _registered_method=True)
        self.GetNextCoinId = channel.unary_unary(
                '/antx.chain.exchange.Query/GetNextCoinId',
                request_serializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetNextCoinIdRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetNextCoinIdResponse.FromString,
                _registered_method=True)
        self.GetExchange = channel.unary_unary(
                '/antx.chain.exchange.Query/GetExchange',
                request_serializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetExchangeRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetExchangeResponse.FromString,
                _registered_method=True)
        self.ListExchange = channel.unary_unary(
                '/antx.chain.exchange.Query/ListExchange',
                request_serializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryListExchangeRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryListExchangeResponse.FromString,
                _registered_method=True)
        self.GetNextExchangeId = channel.unary_unary(
                '/antx.chain.exchange.Query/GetNextExchangeId',
                request_serializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetNextExchangeIdRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetNextExchangeIdResponse.FromString,
                _registered_method=True)


class QueryServicer(object):
    """Query defines the gRPC querier service.
    """

    def Params(self, request, context):
        """Parameters queries the parameters of the module.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoin(self, request, context):
        """根据id查询coin信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCoin(self, request, context):
        """翻页查询coin信息列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextCoinId(self, request, context):
        """查询下一个可用的coinId
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExchange(self, request, context):
        """根据id查询exchange信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExchange(self, request, context):
        """翻页查询exchange信息列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextExchangeId(self, request, context):
        """查询下一个可用的exchangeId
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Params': grpc.unary_unary_rpc_method_handler(
                    servicer.Params,
                    request_deserializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryParamsRequest.FromString,
                    response_serializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryParamsResponse.SerializeToString,
            ),
            'GetCoin': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoin,
                    request_deserializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetCoinRequest.FromString,
                    response_serializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetCoinResponse.SerializeToString,
            ),
            'ListCoin': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCoin,
                    request_deserializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryListCoinRequest.FromString,
                    response_serializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryListCoinResponse.SerializeToString,
            ),
            'GetNextCoinId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextCoinId,
                    request_deserializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetNextCoinIdRequest.FromString,
                    response_serializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetNextCoinIdResponse.SerializeToString,
            ),
            'GetExchange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExchange,
                    request_deserializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetExchangeRequest.FromString,
                    response_serializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetExchangeResponse.SerializeToString,
            ),
            'ListExchange': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExchange,
                    request_deserializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryListExchangeRequest.FromString,
                    response_serializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryListExchangeResponse.SerializeToString,
            ),
            'GetNextExchangeId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextExchangeId,
                    request_deserializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetNextExchangeIdRequest.FromString,
                    response_serializer=antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetNextExchangeIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antx.chain.exchange.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antx.chain.exchange.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Query defines the gRPC querier service.
    """

    @staticmethod
    def Params(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.exchange.Query/Params',
            antx_dot_chain_dot_exchange_dot_query__pb2.QueryParamsRequest.SerializeToString,
            antx_dot_chain_dot_exchange_dot_query__pb2.QueryParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.exchange.Query/GetCoin',
            antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetCoinRequest.SerializeToString,
            antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetCoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.exchange.Query/ListCoin',
            antx_dot_chain_dot_exchange_dot_query__pb2.QueryListCoinRequest.SerializeToString,
            antx_dot_chain_dot_exchange_dot_query__pb2.QueryListCoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextCoinId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.exchange.Query/GetNextCoinId',
            antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetNextCoinIdRequest.SerializeToString,
            antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetNextCoinIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.exchange.Query/GetExchange',
            antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetExchangeRequest.SerializeToString,
            antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetExchangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListExchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.exchange.Query/ListExchange',
            antx_dot_chain_dot_exchange_dot_query__pb2.QueryListExchangeRequest.SerializeToString,
            antx_dot_chain_dot_exchange_dot_query__pb2.QueryListExchangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextExchangeId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.exchange.Query/GetNextExchangeId',
            antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetNextExchangeIdRequest.SerializeToString,
            antx_dot_chain_dot_exchange_dot_query__pb2.QueryGetNextExchangeIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
