# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from antx.chain.agent import query_pb2 as antx_dot_chain_dot_agent_dot_query__pb2


class QueryStub(object):
    """Query defines the gRPC querier service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Params = channel.unary_unary(
                '/antx.chain.agent.Query/Params',
                request_serializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryParamsRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryParamsResponse.FromString,
                _registered_method=True)
        self.GetAgentBinding = channel.unary_unary(
                '/antx.chain.agent.Query/GetAgentBinding',
                request_serializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryGetAgentBindingRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryGetAgentBindingResponse.FromString,
                _registered_method=True)
        self.ListAgentBinding = channel.unary_unary(
                '/antx.chain.agent.Query/ListAgentBinding',
                request_serializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryListAgentBindingRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryListAgentBindingResponse.FromString,
                _registered_method=True)
        self.ListAgentBindingByChainAddress = channel.unary_unary(
                '/antx.chain.agent.Query/ListAgentBindingByChainAddress',
                request_serializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryListAgentBindingByChainAddressRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryListAgentBindingByChainAddressResponse.FromString,
                _registered_method=True)


class QueryServicer(object):
    """Query defines the gRPC querier service.
    """

    def Params(self, request, context):
        """Parameters queries the parameters of the module.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentBinding(self, request, context):
        """根据agent地址查询绑定关系
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgentBinding(self, request, context):
        """翻页查询绑定关系
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgentBindingByChainAddress(self, request, context):
        """根据链地址翻页查询绑定关系
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Params': grpc.unary_unary_rpc_method_handler(
                    servicer.Params,
                    request_deserializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryParamsRequest.FromString,
                    response_serializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryParamsResponse.SerializeToString,
            ),
            'GetAgentBinding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentBinding,
                    request_deserializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryGetAgentBindingRequest.FromString,
                    response_serializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryGetAgentBindingResponse.SerializeToString,
            ),
            'ListAgentBinding': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgentBinding,
                    request_deserializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryListAgentBindingRequest.FromString,
                    response_serializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryListAgentBindingResponse.SerializeToString,
            ),
            'ListAgentBindingByChainAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgentBindingByChainAddress,
                    request_deserializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryListAgentBindingByChainAddressRequest.FromString,
                    response_serializer=antx_dot_chain_dot_agent_dot_query__pb2.QueryListAgentBindingByChainAddressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antx.chain.agent.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antx.chain.agent.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Query defines the gRPC querier service.
    """

    @staticmethod
    def Params(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.agent.Query/Params',
            antx_dot_chain_dot_agent_dot_query__pb2.QueryParamsRequest.SerializeToString,
            antx_dot_chain_dot_agent_dot_query__pb2.QueryParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentBinding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.agent.Query/GetAgentBinding',
            antx_dot_chain_dot_agent_dot_query__pb2.QueryGetAgentBindingRequest.SerializeToString,
            antx_dot_chain_dot_agent_dot_query__pb2.QueryGetAgentBindingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgentBinding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.agent.Query/ListAgentBinding',
            antx_dot_chain_dot_agent_dot_query__pb2.QueryListAgentBindingRequest.SerializeToString,
            antx_dot_chain_dot_agent_dot_query__pb2.QueryListAgentBindingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgentBindingByChainAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.agent.Query/ListAgentBindingByChainAddress',
            antx_dot_chain_dot_agent_dot_query__pb2.QueryListAgentBindingByChainAddressRequest.SerializeToString,
            antx_dot_chain_dot_agent_dot_query__pb2.QueryListAgentBindingByChainAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
