# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antx/chain/funding/params.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61ntx/chain/funding/params.proto\x12\x12\x61ntx.chain.funding\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\"M\n\x06Params\x12#\n\rowner_address\x18\x01 \x03(\tR\x0cownerAddress:\x1e\xe8\xa0\x1f\x01\x8a\xe7\xb0*\x15\x61ntx/x/funding/ParamsBd\n!exchange.antx.proto.chain.fundingB\x0bParamsProtoP\x01Z,github.com/antxprotocol/antx/x/funding/types\xf0\xe1\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antx.chain.funding.params_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!exchange.antx.proto.chain.fundingB\013ParamsProtoP\001Z,github.com/antxprotocol/antx/x/funding/types\360\341\036\001'
  _globals['_PARAMS']._options = None
  _globals['_PARAMS']._serialized_options = b'\350\240\037\001\212\347\260*\025antx/x/funding/Params'
  _globals['_PARAMS']._serialized_start=96
  _globals['_PARAMS']._serialized_end=173
# @@protoc_insertion_point(module_scope)
