# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antex/server/asset/asset_rpc.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'antex/server/asset/asset_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antex_proto.antex.server.asset import asset_type_pb2 as antex_dot_server_dot_asset_dot_asset__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"antex/server/asset/asset_rpc.proto\x12\x12\x61ntex.server.asset\x1a#antex/server/asset/asset_type.proto2\x88\x07\n\x0c\x41ssetService\x12R\n\x07\x44\x65posit\x12\".antex.server.asset.DepositRequest\x1a#.antex.server.asset.DepositResponse\x12|\n\x15\x42lockConfirmedDeposit\x12\x30.antex.server.asset.BlockConfirmedDepositRequest\x1a\x31.antex.server.asset.BlockConfirmedDepositResponse\x12\x88\x01\n\x19ValidatorConfirmedDeposit\x12\x34.antex.server.asset.ValidatorConfirmedDepositRequest\x1a\x35.antex.server.asset.ValidatorConfirmedDepositResponse\x12\x61\n\x0cQueryDeposit\x12\'.antex.server.asset.QueryDepositRequest\x1a(.antex.server.asset.QueryDepositResponse\x12U\n\x08Withdraw\x12#.antex.server.asset.WithdrawRequest\x1a$.antex.server.asset.WithdrawResponse\x12\x8b\x01\n\x1aValidatorConfirmedWithdraw\x12\x35.antex.server.asset.ValidatorConfirmedWithdrawRequest\x1a\x36.antex.server.asset.ValidatorConfirmedWithdrawResponse\x12m\n\x10WithdrawFinished\x12+.antex.server.asset.WithdrawFinishedRequest\x1a,.antex.server.asset.WithdrawFinishedResponse\x12\x64\n\rQueryWithdraw\x12(.antex.server.asset.QueryWithdrawRequest\x1a).antex.server.asset.QueryWithdrawResponseB4\n!exchange.antex.proto.server.assetB\rAssetRpcProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antex.server.asset.asset_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!exchange.antex.proto.server.assetB\rAssetRpcProtoP\001'
  _globals['_ASSETSERVICE']._serialized_start=96
  _globals['_ASSETSERVICE']._serialized_end=1000
# @@protoc_insertion_point(module_scope)
