# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from antx.chain.subaccount import query_pb2 as antx_dot_chain_dot_subaccount_dot_query__pb2


class QueryStub(object):
    """Query defines the gRPC querier service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Params = channel.unary_unary(
                '/antx.chain.subaccount.Query/Params',
                request_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryParamsRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryParamsResponse.FromString,
                _registered_method=True)
        self.GetSubaccount = channel.unary_unary(
                '/antx.chain.subaccount.Query/GetSubaccount',
                request_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountResponse.FromString,
                _registered_method=True)
        self.ListSubaccount = channel.unary_unary(
                '/antx.chain.subaccount.Query/ListSubaccount',
                request_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListSubaccountRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListSubaccountResponse.FromString,
                _registered_method=True)
        self.GetSubaccountByChainAddress = channel.unary_unary(
                '/antx.chain.subaccount.Query/GetSubaccountByChainAddress',
                request_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountByChainAddressRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountByChainAddressResponse.FromString,
                _registered_method=True)
        self.ListSubaccountByChainAddress = channel.unary_unary(
                '/antx.chain.subaccount.Query/ListSubaccountByChainAddress',
                request_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListSubaccountByChainAddressRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListSubaccountByChainAddressResponse.FromString,
                _registered_method=True)
        self.GetSubaccountAsset = channel.unary_unary(
                '/antx.chain.subaccount.Query/GetSubaccountAsset',
                request_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountAssetRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountAssetResponse.FromString,
                _registered_method=True)
        self.ListPerpetualAsset = channel.unary_unary(
                '/antx.chain.subaccount.Query/ListPerpetualAsset',
                request_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListPerpetualAssetRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListPerpetualAssetResponse.FromString,
                _registered_method=True)
        self.GetSubaccountAvailableWithdrawBalance = channel.unary_unary(
                '/antx.chain.subaccount.Query/GetSubaccountAvailableWithdrawBalance',
                request_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountAvailableWithdrawBalanceRequest.SerializeToString,
                response_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountAvailableWithdrawBalanceResponse.FromString,
                _registered_method=True)


class QueryServicer(object):
    """Query defines the gRPC querier service.
    """

    def Params(self, request, context):
        """Parameters queries the parameters of the module.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubaccount(self, request, context):
        """根据subaccountId查询subaccount信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSubaccount(self, request, context):
        """翻页查询subaccount信息列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubaccountByChainAddress(self, request, context):
        """根据chainType&chainAddress和clientAccountId查询subaccount信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSubaccountByChainAddress(self, request, context):
        """根据chainType&chainAddress翻页查询subaccount信息列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubaccountAsset(self, request, context):
        """根据subaccountId查询账号下资产
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPerpetualAsset(self, request, context):
        """翻页查询perpetualAsset信息列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubaccountAvailableWithdrawBalance(self, request, context):
        """根据subaccountId查询账号可用提现余额
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Params': grpc.unary_unary_rpc_method_handler(
                    servicer.Params,
                    request_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryParamsRequest.FromString,
                    response_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryParamsResponse.SerializeToString,
            ),
            'GetSubaccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubaccount,
                    request_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountRequest.FromString,
                    response_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountResponse.SerializeToString,
            ),
            'ListSubaccount': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSubaccount,
                    request_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListSubaccountRequest.FromString,
                    response_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListSubaccountResponse.SerializeToString,
            ),
            'GetSubaccountByChainAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubaccountByChainAddress,
                    request_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountByChainAddressRequest.FromString,
                    response_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountByChainAddressResponse.SerializeToString,
            ),
            'ListSubaccountByChainAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSubaccountByChainAddress,
                    request_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListSubaccountByChainAddressRequest.FromString,
                    response_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListSubaccountByChainAddressResponse.SerializeToString,
            ),
            'GetSubaccountAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubaccountAsset,
                    request_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountAssetRequest.FromString,
                    response_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountAssetResponse.SerializeToString,
            ),
            'ListPerpetualAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPerpetualAsset,
                    request_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListPerpetualAssetRequest.FromString,
                    response_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListPerpetualAssetResponse.SerializeToString,
            ),
            'GetSubaccountAvailableWithdrawBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubaccountAvailableWithdrawBalance,
                    request_deserializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountAvailableWithdrawBalanceRequest.FromString,
                    response_serializer=antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountAvailableWithdrawBalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antx.chain.subaccount.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antx.chain.subaccount.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Query defines the gRPC querier service.
    """

    @staticmethod
    def Params(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.subaccount.Query/Params',
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryParamsRequest.SerializeToString,
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubaccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.subaccount.Query/GetSubaccount',
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountRequest.SerializeToString,
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSubaccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.subaccount.Query/ListSubaccount',
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListSubaccountRequest.SerializeToString,
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListSubaccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubaccountByChainAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.subaccount.Query/GetSubaccountByChainAddress',
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountByChainAddressRequest.SerializeToString,
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountByChainAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSubaccountByChainAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.subaccount.Query/ListSubaccountByChainAddress',
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListSubaccountByChainAddressRequest.SerializeToString,
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListSubaccountByChainAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubaccountAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.subaccount.Query/GetSubaccountAsset',
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountAssetRequest.SerializeToString,
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountAssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPerpetualAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.subaccount.Query/ListPerpetualAsset',
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListPerpetualAssetRequest.SerializeToString,
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryListPerpetualAssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubaccountAvailableWithdrawBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.subaccount.Query/GetSubaccountAvailableWithdrawBalance',
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountAvailableWithdrawBalanceRequest.SerializeToString,
            antx_dot_chain_dot_subaccount_dot_query__pb2.QueryGetSubaccountAvailableWithdrawBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
