# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from antx.chain.vault import tx_pb2 as antx_dot_chain_dot_vault_dot_tx__pb2


class MsgStub(object):
    """Msg defines the vault Msg service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateParams = channel.unary_unary(
                '/antx.chain.vault.Msg/UpdateParams',
                request_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateParams.SerializeToString,
                response_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateParamsResponse.FromString,
                _registered_method=True)
        self.CreateVault = channel.unary_unary(
                '/antx.chain.vault.Msg/CreateVault',
                request_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgCreateVault.SerializeToString,
                response_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgCreateVaultResponse.FromString,
                _registered_method=True)
        self.DeleteVault = channel.unary_unary(
                '/antx.chain.vault.Msg/DeleteVault',
                request_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgDeleteVault.SerializeToString,
                response_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgDeleteVaultResponse.FromString,
                _registered_method=True)
        self.DepositToVault = channel.unary_unary(
                '/antx.chain.vault.Msg/DepositToVault',
                request_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgDepositToVault.SerializeToString,
                response_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgDepositToVaultResponse.FromString,
                _registered_method=True)
        self.WithdrawFromVault = channel.unary_unary(
                '/antx.chain.vault.Msg/WithdrawFromVault',
                request_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgWithdrawFromVault.SerializeToString,
                response_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgWithdrawFromVaultResponse.FromString,
                _registered_method=True)
        self.UpdateOperatorParams = channel.unary_unary(
                '/antx.chain.vault.Msg/UpdateOperatorParams',
                request_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateOperatorParams.SerializeToString,
                response_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateOperatorParamsResponse.FromString,
                _registered_method=True)
        self.ApproveWithdraw = channel.unary_unary(
                '/antx.chain.vault.Msg/ApproveWithdraw',
                request_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgApproveWithdraw.SerializeToString,
                response_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgApproveWithdrawResponse.FromString,
                _registered_method=True)
        self.UpdateVaultStatus = channel.unary_unary(
                '/antx.chain.vault.Msg/UpdateVaultStatus',
                request_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateVaultStatus.SerializeToString,
                response_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateVaultStatusResponse.FromString,
                _registered_method=True)


class MsgServicer(object):
    """Msg defines the vault Msg service.
    """

    def UpdateParams(self, request, context):
        """UpdateParams defines a (governance) operation for updating the module
        parameters. The authority defaults to the x/gov module account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVault(self, request, context):
        """CreateVault creates a new vault for the sender
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVault(self, request, context):
        """DeleteVault deletes an existing vault
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DepositToVault(self, request, context):
        """DepositToVault deposits funds into vault.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WithdrawFromVault(self, request, context):
        """WithdrawFromVault withdraws shares from vault.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOperatorParams(self, request, context):
        """UpdateOperatorParams sets the parameters regarding megavault operator.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveWithdraw(self, request, context):
        """ApproveWithdraw approves and executes withdrawal requests in batch.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVaultStatus(self, request, context):
        """UpdateVaultStatus updates the status of a vault.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateParams': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParams,
                    request_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateParams.FromString,
                    response_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateParamsResponse.SerializeToString,
            ),
            'CreateVault': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVault,
                    request_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgCreateVault.FromString,
                    response_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgCreateVaultResponse.SerializeToString,
            ),
            'DeleteVault': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVault,
                    request_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgDeleteVault.FromString,
                    response_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgDeleteVaultResponse.SerializeToString,
            ),
            'DepositToVault': grpc.unary_unary_rpc_method_handler(
                    servicer.DepositToVault,
                    request_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgDepositToVault.FromString,
                    response_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgDepositToVaultResponse.SerializeToString,
            ),
            'WithdrawFromVault': grpc.unary_unary_rpc_method_handler(
                    servicer.WithdrawFromVault,
                    request_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgWithdrawFromVault.FromString,
                    response_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgWithdrawFromVaultResponse.SerializeToString,
            ),
            'UpdateOperatorParams': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOperatorParams,
                    request_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateOperatorParams.FromString,
                    response_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateOperatorParamsResponse.SerializeToString,
            ),
            'ApproveWithdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveWithdraw,
                    request_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgApproveWithdraw.FromString,
                    response_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgApproveWithdrawResponse.SerializeToString,
            ),
            'UpdateVaultStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVaultStatus,
                    request_deserializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateVaultStatus.FromString,
                    response_serializer=antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateVaultStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antx.chain.vault.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('antx.chain.vault.Msg', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Msg defines the vault Msg service.
    """

    @staticmethod
    def UpdateParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.vault.Msg/UpdateParams',
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateParams.SerializeToString,
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.vault.Msg/CreateVault',
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgCreateVault.SerializeToString,
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgCreateVaultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.vault.Msg/DeleteVault',
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgDeleteVault.SerializeToString,
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgDeleteVaultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DepositToVault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.vault.Msg/DepositToVault',
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgDepositToVault.SerializeToString,
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgDepositToVaultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WithdrawFromVault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.vault.Msg/WithdrawFromVault',
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgWithdrawFromVault.SerializeToString,
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgWithdrawFromVaultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOperatorParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.vault.Msg/UpdateOperatorParams',
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateOperatorParams.SerializeToString,
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateOperatorParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveWithdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.vault.Msg/ApproveWithdraw',
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgApproveWithdraw.SerializeToString,
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgApproveWithdrawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVaultStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/antx.chain.vault.Msg/UpdateVaultStatus',
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateVaultStatus.SerializeToString,
            antx_dot_chain_dot_vault_dot_tx__pb2.MsgUpdateVaultStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
