# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antex/chain/offchain/query.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'antex/chain/offchain/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antex_proto.amino import amino_pb2 as amino_dot_amino__pb2
from antex_proto.antex.chain.offchain import offchain_pb2 as antex_dot_chain_dot_offchain_dot_offchain__pb2
from antex_proto.antex.chain.offchain import params_pb2 as antex_dot_chain_dot_offchain_dot_params__pb2
from antex_proto.cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from antex_proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n antex/chain/offchain/query.proto\x12\x14\x61ntex.chain.offchain\x1a\x11\x61mino/amino.proto\x1a#antex/chain/offchain/offchain.proto\x1a!antex/chain/offchain/params.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\"\x14\n\x12QueryParamsRequest\"V\n\x13QueryParamsResponse\x12?\n\x06params\x18\x01 \x01(\x0b\x32\x1c.antex.chain.offchain.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\"\x1e\n\x1cQueryGetEventSequenceRequest\"F\n\x1dQueryGetEventSequenceResponse\x12%\n\x0e\x65vent_sequence\x18\x01 \x01(\x04R\reventSequence\"!\n\x1fQueryOffchainEventStreamRequest\"n\n QueryOffchainEventStreamResponse\x12J\n\x0eoffchain_event\x18\x01 \x03(\x0b\x32#.antex.chain.offchain.OffchainEventR\roffchainEvent2\x8c\x03\n\x05Query\x12}\n\x06Params\x12(.antex.chain.offchain.QueryParamsRequest\x1a).antex.chain.offchain.QueryParamsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/antex/offchain/params\x12{\n\x10GetEventSequence\x12\x32.antex.chain.offchain.QueryGetEventSequenceRequest\x1a\x33.antex.chain.offchain.QueryGetEventSequenceResponse\x12\x86\x01\n\x13OffchainEventStream\x12\x35.antex.chain.offchain.QueryOffchainEventStreamRequest\x1a\x36.antex.chain.offchain.QueryOffchainEventStreamResponse0\x01\x42h\n#exchange.antex.proto.chain.offchainB\nQueryProtoP\x01Z/github.com/antexprotocol/antex/x/offchain/types\xf0\xe1\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antex.chain.offchain.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#exchange.antex.proto.chain.offchainB\nQueryProtoP\001Z/github.com/antexprotocol/antex/x/offchain/types\360\341\036\001'
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._loaded_options = None
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_QUERY'].methods_by_name['Params']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Params']._serialized_options = b'\202\323\344\223\002\030\022\026/antex/offchain/params'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=245
  _globals['_QUERYPARAMSREQUEST']._serialized_end=265
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=267
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=353
  _globals['_QUERYGETEVENTSEQUENCEREQUEST']._serialized_start=355
  _globals['_QUERYGETEVENTSEQUENCEREQUEST']._serialized_end=385
  _globals['_QUERYGETEVENTSEQUENCERESPONSE']._serialized_start=387
  _globals['_QUERYGETEVENTSEQUENCERESPONSE']._serialized_end=457
  _globals['_QUERYOFFCHAINEVENTSTREAMREQUEST']._serialized_start=459
  _globals['_QUERYOFFCHAINEVENTSTREAMREQUEST']._serialized_end=492
  _globals['_QUERYOFFCHAINEVENTSTREAMRESPONSE']._serialized_start=494
  _globals['_QUERYOFFCHAINEVENTSTREAMRESPONSE']._serialized_end=604
  _globals['_QUERY']._serialized_start=607
  _globals['_QUERY']._serialized_end=1003
# @@protoc_insertion_point(module_scope)
