# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antex/server/funding/funding_rpc.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'antex/server/funding/funding_rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from antex_proto.antex.chain.funding import funding_pb2 as antex_dot_chain_dot_funding_dot_funding__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&antex/server/funding/funding_rpc.proto\x12\x14\x61ntex.server.funding\x1a!antex/chain/funding/funding.proto\"\xb0\x02\n\x19GetFundingRatePageRequest\x12\x1f\n\x0b\x65xchange_id\x18\x01 \x01(\x04R\nexchangeId\x12\x12\n\x04size\x18\x02 \x01(\rR\x04size\x12\x1f\n\x0boffset_data\x18\x03 \x01(\tR\noffsetData\x12\x43\n\x1e\x66ilter_settlement_funding_rate\x18\x04 \x01(\x08R\x1b\x66ilterSettlementFundingRate\x12=\n\x1b\x66ilter_begin_time_inclusive\x18\x05 \x01(\x04R\x18\x66ilterBeginTimeInclusive\x12\x39\n\x19\x66ilter_end_time_exclusive\x18\x06 \x01(\x04R\x16\x66ilterEndTimeExclusive\"\x94\x01\n\x1aGetFundingRatePageResponse\x12\x43\n\x0c\x66unding_rate\x18\x01 \x03(\x0b\x32 .antex.chain.funding.FundingTickR\x0b\x66undingRate\x12\x31\n\x15next_page_offset_data\x18\x02 \x01(\tR\x12nextPageOffsetData2\x89\x01\n\x0e\x46undingService\x12w\n\x12GetFundingRatePage\x12/.antex.server.funding.GetFundingRatePageRequest\x1a\x30.antex.server.funding.GetFundingRatePageResponseB8\n#exchange.antex.proto.server.fundingB\x0f\x46undingRpcProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antex.server.funding.funding_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#exchange.antex.proto.server.fundingB\017FundingRpcProtoP\001'
  _globals['_GETFUNDINGRATEPAGEREQUEST']._serialized_start=100
  _globals['_GETFUNDINGRATEPAGEREQUEST']._serialized_end=404
  _globals['_GETFUNDINGRATEPAGERESPONSE']._serialized_start=407
  _globals['_GETFUNDINGRATEPAGERESPONSE']._serialized_end=555
  _globals['_FUNDINGSERVICE']._serialized_start=558
  _globals['_FUNDINGSERVICE']._serialized_end=695
# @@protoc_insertion_point(module_scope)
